### ISSUE TITLE
Python script not running

### ISSUE THREAD

**Issue by ProdigizedDP** [CloudDCrow/Shiny-Loops#1]
I've tried messing around with it for an hour or two and can't really get it to work , I'm not really experienced with python at all but when I run the script I receive an error in a couple of the files one of them being 

\shiny-loops-main\modules\button_presser.py", line 2, in <module>
    import win32con
ModuleNotFoundError: No module named 'win32con'

Idk if there's a way for me to share like a crash log or anything.

**Comment by BrianDurham** [comment]
Hi - it sounds like you need to install pypiwin32. It contains win32con. Typically that's done via a 'pip install' command:

'pip install pypiwin32' or 'python -m pip install --upgrade pypiwin32'

Hopefully CloudDCrow will update his README about the need for pywin32 and how to install it if needed.

**Comment by CloudDCrow** [comment]
Yes, the above response should work, but I have created a requirements.txt file that includes all the packages that need to be installed with pip.

I also updated the README file to include an installation guide.

Hopefully, it will be clearer how to run it. If it's still not clear enough, I will try to make a video explanation.
